global using System.Net;
global using System.Net.Http;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using System.Net.Sockets;
global using System.Text;
global using System.Text.Json;
global using System.Threading.Tasks;
global using Microsoft.Extensions.DependencyInjection;
